# Generated by Django 4.1.3 on 2022-11-16 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groovy', '0002_songs_artist_songs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='name',
            new_name='title',
        ),
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.CharField(max_length=100)),
                ('songs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groovy.songs')),
            ],
        ),
    ]
