# Generated by Django 4.1.3 on 2022-11-18 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groovy', '0002_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groovy.artists')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groovy.genres')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
