# Generated by Django 4.1.3 on 2022-11-18 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groovy', '0003_albums'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=4)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groovy.albums')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groovy.artists')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groovy.genres')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
