# Generated by Django 4.1.3 on 2022-11-18 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groovy', '0005_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongsInPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groovy.playlist')),
                ('songs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groovy.songs')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
